### ISSUE TITLE
Compatibility with older OSX versions?

### ISSUE THREAD

**Issue by esaruoho** [kevingessner/FunctionFlip#16]
Would be lovely if there was some info about the earliest OSX that will run this app.

For intance, I'd love to install this on OSX 10.6.8 Snow Leopard, but have no idea if it would work or not.

**Comment by kevingessner** [comment]
The current version may or may not work with OS X 10.6, but older versions are available for download at http://kevingessner.com/software/functionflip. 2.1 and 2.2 should work well on 10.6.
