### ISSUE TITLE
Function key list is white and unreadable when dark mode is on

### ISSUE THREAD

**Issue by antipex** [kevingessner/FunctionFlip#18]
When dark mode is enabled the function key list in the pref pane has a white background, and is therefore completely unreadable without clicking on each item.

**Comment by DATEx2** [comment]
4 years later and the issue is still present

**Comment by kevingessner** [comment]
Regrettably, I am no longer able to maintain FunctionFlip. Others are welcome to fork and distribute under the terms of the license.
