### ISSUE TITLE
FunctionFlip seems to have stopped working on MacOS 10.11.3

### ISSUE THREAD

**Issue by depsypher** [kevingessner/FunctionFlip#3]
Here's what shows up in Console.app when clicking Stop/Start. FunctionFlip version 2.2.3.

2/4/16 10:54:34.716 AM System Preferences[30237]: starting /Users/ray/Library/PreferencePanes/FunctionFlip.prefPane/Contents/Resources/FunctionFlip.app
2/4/16 10:54:34.781 AM launchservicesd[90]: SecTaskLoadEntitlements failed error=22
2/4/16 10:54:34.787 AM launchservicesd[90]: SecTaskLoadEntitlements failed error=22
2/4/16 10:54:34.800 AM appleeventsd[59]: SecTaskLoadEntitlements failed error=22
2/4/16 10:54:34.840 AM WindowServer[196]: SecTaskLoadEntitlements failed error=22
2/4/16 10:54:34.840 AM tccd[423]: SecTaskLoadEntitlements failed error=22
2/4/16 10:54:34.850 AM tccd[423]: SecTaskLoadEntitlements failed error=22
2/4/16 10:54:39.929 AM WindowServer[196]: send_datagram_available_ping: pid 550 failed to act on a ping it dequeued before timing out.
2/4/16 10:54:40.068 AM WindowServer[196]: Surface testing disallowed updates for 10 sequential attempts...
2/4/16 10:54:40.078 AM WindowServer[196]: Surface test allowed updates after 11 attempts (44 ms)
2/4/16 10:54:50.078 AM WindowServer[196]: send_datagram_available_ping: pid 550 failed to act on a ping it dequeued before timing out.
2/4/16 10:55:00.451 AM WindowServer[196]: send_datagram_available_ping: pid 550 failed to act on a ping it dequeued before timing out.

**Comment by nikonratm** [comment]
Oddly I don't get these error messages but it is also stopped working for me under 10.11.3

**Comment by spencermathews** [comment]
Likewise, I'm getting the same errors on 10.11.4 with FunctionFlip 2.2.3.

For what it's worth, FunctionFlip works fine when I log in, but at some point the remapping fails and F4 brings up Dashboard instead of Launchpad.

Thanks for developing this useful tool, and please let me know if there is any way I can help you get to the bottom of this.

```
5/17/16 3:45:46.225 PM System Preferences[2816]: starting /opt/homebrew-cask/Caskroom/functionflip/2.2.3/FunctionFlip.prefPane/Contents/Resources/FunctionFlip.app
5/17/16 3:45:46.273 PM launchservicesd[78]: SecTaskLoadEntitlements failed error=22
5/17/16 3:45:46.277 PM launchservicesd[78]: SecTaskLoadEntitlements failed error=22
5/17/16 3:45:46.291 PM appleeventsd[52]: SecTaskLoadEntitlements failed error=22
5/17/16 3:45:46.339 PM WindowServer[183]: SecTaskLoadEntitlements failed error=22
5/17/16 3:45:46.340 PM tccd[320]: SecTaskLoadEntitlements failed error=22
5/17/16 3:45:46.355 PM tccd[320]: SecTaskLoadEntitlements failed error=22
```

**Comment by kevingessner** [comment]
Not reproducible here -- FunctionFlip 2.2.3 works fine on 10.11 and 10.12.  The logs stating "entitlement failures" may be a sign that this is related to security settings; FunctionFlip is not a signed app so it needs to be allowed explicitly.
