### ISSUE TITLE
Memory leaks in FunctionFlip

### ISSUE THREAD

**Issue by cbowns** [kevingessner/FunctionFlip#5]
After a few weeks of running in the background, FunctionFlip is up to 1.12 GB of resident memory usage.

`leaks` tells it like it is: `Process 1268: 6028548 leaks for 1114248080 total leaked bytes.` (1.03 GiB)

Apple's [Developer Center article](https://developer.apple.com/library/mac/documentation/Performance/Conceptual/ManagingMemory/Articles/FindingLeaks.html#//apple_ref/doc/uid/20001883-100980) has tips for running the application with `MallocStackLogging` and other flags enabled to help trace these down.

**Comment by cbowns** [comment]
(I used to hunt these at Apple in the graphics team, so I can help trace these down, but I wanted to file this issue first and investigate later.)

**Comment by mdevils** [comment]
I confirm this is a problem. After a few weeks it grew up to 2.3GB memory.

**Comment by kevingessner** [comment]
Will be fixed in 2.2.4, out shortly, via https://github.com/kevingessner/FunctionFlip/pull/1
